# Generated by Django 4.2.1 on 2023-05-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url', models.URLField(unique=True)),
                ('keyword', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Filtered_Url',
            },
        ),
    ]
