# Generated by Django 4.2.2 on 2023-07-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url', models.URLField(unique=True)),
                ('keyword', models.CharField(max_length=255)),
                ('keyword_found', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Entered_Url',
            },
        ),
    ]
