# Generated by Django 4.2.1 on 2023-05-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urls',
            options={'verbose_name_plural': 'Entered_Url'},
        ),
        migrations.AddField(
            model_name='urls',
            name='keyword_found',
            field=models.BooleanField(default=False),
        ),
    ]
